import Head from 'next/head';
import Image from 'next/image';
import styles from './Layout.module.css';

const Layout = ({ children }) => {
     return (
          <div className={`${styles.layout} font-poppins text-main`}>
               <Head>
                    <title>68-kv</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="minimum-scale=1, initial-scale=1, width=device-width" />
                    <link rel="icon" href="/68-kv.jpg" />
               </Head>
               <header>
                    <Image src="/68-kv-icon.svg" width={70} height={50} alt="" />
               </header>

               <main className="p-6">
                    {children}
               </main>

               <footer className="text-secondary text-center my-4 text-sm">nosirovabosjon3429@gmail.com</footer>

          </div>
     )
}

export default Layout;
